### ISSUE TITLE
Custom Copybara file support might be broken?

### ISSUE THREAD

**Issue by PhilipVinc** [Olivr/copybara-action#130]
I am using the following GitHub action yml file:
```python
on:
  push:
jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: olivr/copybara-action@v1.2.4
        with:
          ssh_key: ${{ secrets.GH_BOT_SSH_PRIV_KEY }}
          access_token: ${{ secrets.GH_BOT_GITHUB_TOKEN }}
          sot_repo: NeuralQXLab/omnia
          destination_repo: NeuralQXLab/netket_pro
          custom_config: config/copybara/copy.bara.sky
```

But I see a failure when running, and in debug mode the error is
```bash

##[debug]Result: '***'
##[debug]Loading env
Run olivr/copybara-action@v1.2.4
  with:
    ssh_key: ***
    access_token: ***
    sot_repo: NeuralQXLab/omnia
    destination_repo: NeuralQXLab/netket_pro
    custom_config: config/copybara/copy.bara.sky
    push_include: **
    pr_include: **
    committer: Github Actions <actions@github.com>
    copybara_image: olivr/copybara
    copybara_image_tag: latest
    create_repo: yes
##[debug]BEWARE: Debug mode is on, this could result in this action succeeding while it didn't. Check the logs.
##[debug]Save config files
/home/runner/work/_actions/olivr/copybara-action/v1.2.4/dist/index.js:136182
                    const configFile = path_1.default.join(process.cwd(), this.config.customConfig);
                                                      ^
TypeError: Cannot read properties of undefined (reading 'join')
    at CopybaraAction.<anonymous> (/home/runner/work/_actions/olivr/copybara-action/v1.2.4/dist/index.js:136182:55)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/olivr/copybara-action/v1.2.4/dist/index.js:136062:71
    at new Promise (<anonymous>)
    at __webpack_modules__.94675.__awaiter (/home/runner/work/_actions/olivr/copybara-action/v1.2.4/dist/index.js:136058:12)
    at CopybaraAction.getCopybaraConfig (/home/runner/work/_actions/olivr/copybara-action/v1.2.4/dist/index.js:136179:16)
    at CopybaraAction.<anonymous> (/home/runner/work/_actions/olivr/copybara-action/v1.2.4/dist/index.js:136201:76)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/olivr/copybara-action/v1.2.4/dist/index.js:136059:58)
Node.js v20.13.1
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Run olivr/copybara-action@v1.2.4
```

I'm not familiar with node, so I don't fully understand everything, but it seems to me that `path` in here is not set? 
https://github.com/Olivr/copybara-action/blob/c6f5210bbf4b3a520d180dcde017bde84f6015a9/src/copybaraAction.ts#L130

**Comment by hoonahn** [comment]
facing same issue. any updates?

**Comment by politician** [comment]
Hi @PhilipVinc @hoonahn Can you please try with the latest version 1.2.5 which should fix this issue ?
